# NOTE: settings in this file have precedence over settings on the website
image: 
  - Visual Studio 2013
  - Visual Studio 2019

matrix:
  fast_finish: true
  exclude:
    - platform: x64
      TOOLCHAIN_VERSION: 10.0
    - platform: Win32
      TOOLCHAIN_VERSION: 10.0
      image: Visual Studio 2019
    - TOOLCHAIN_VERSION: 12.0
      image: Visual Studio 2019
    - platform: Win32
      TOOLCHAIN_VERSION: 16.0
    - platform: x64
      TOOLCHAIN_VERSION: 16.0
      image: Visual Studio 2013

platform:
  - Win32
  - x64

pull_requests:
  do_not_increment_build_number: true

notifications:
  - provider: Email
    to:
      - boinc_cvs@ssl.berkeley.edu
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

branches:
  only:
  - master

skip_tags: true

skip_commits:
  files:
    - .github/
    - 3rdParty/*.sh
    - android/
    - client/android/
    - client/os2/
    - client/scripts/
    - clientgui/gtk/
    - clientgui/mac/
    - clientgui/skins/
    - db/
    - doc/
    - drupal/
    - html/
    - integration_test
    - lib/mac/
    - locale/
    - m4/
    - mac_build/
    - mac_installer/
    - packages/
    - py/
    - stripchart/
    - tests/
    - tools/
    - vda/
    - xcompile/

configuration:
  - Release

environment:
  matrix:
    - TOOLCHAIN_VERSION: 10.0
      solution_name: win_build\boinc_vs2010.sln
      depends_zip_path: https://boinc.berkeley.edu/dl/boinc_depends/boinc_depends_win_vs2010.zip
      depends_path: C:\projects\boinc_depends_win_vs2010
    - TOOLCHAIN_VERSION: 12.0
      solution_name: win_build\boinc_vs2013.sln
      depends_zip_path: https://boinc.berkeley.edu/dl/boinc_depends/boinc_depends_win_vs2013.zip
      depends_path: C:\projects\boinc_depends_win_vs2013
    - TOOLCHAIN_VERSION: 16.0
      solution_name: win_build\boinc_vs2019.sln
  BINTRAY_API_KEY:
    secure: kZI9k0Kh2bFSCbXfkz+J16fGNAee1ToRMl10D8QPQsKpC2PqhF/uVMpd6gRC+OSI
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma2 -mx=9 -ms=on"

cache:
  - C:\projects\boinc_depends_win_vs2010 -> appveyor.yml, win_build\load_dependencies.bat
  - C:\projects\boinc_depends_win_vs2013 -> appveyor.yml, win_build\load_dependencies.bat
  - '%LOCALAPPDATA%\vcpkg\archives -> appveyor.yml'

before_build:
  - if %TOOLCHAIN_VERSION%==10.0 call win_build\load_dependencies.bat %depends_zip_path% %depends_path% %platform% %configuration%
  - if %TOOLCHAIN_VERSION%==12.0 call win_build\load_dependencies.bat %depends_zip_path% %depends_path% %platform% %configuration%
  - if %TOOLCHAIN_VERSION%==10.0 call "%VS100COMNTOOLS%\vsvars32.bat"
  - if %TOOLCHAIN_VERSION%==10.0 call git apply boinc_vs2010.sln.ci.patch
  - if %TOOLCHAIN_VERSION%==12.0 call "%VS120COMNTOOLS%\vsvars32.bat"
  - if %TOOLCHAIN_VERSION%==12.0 call rmdir /S /Q %localappdata%\Microsoft\VisualStudio\%TOOLCHAIN_VERSION%\ComponentModelCache
  - if %TOOLCHAIN_VERSION%==16.0 call "C:\Tools\vcpkg\vcpkg.exe" integrate remove
  - if %TOOLCHAIN_VERSION%==16.0 call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\vsdevcmd.bat"

build_script:
  - msbuild %solution_name% /p:Configuration=%configuration%;Platform=%platform%;VcpkgTripletConfig=ci -m

after_build:
  - if %TOOLCHAIN_VERSION%==12.0 call deploy\prepare_deployment.bat
  - if %TOOLCHAIN_VERSION%==12.0 call deploy\deploy_to_bintray.bat

artifacts:
  - path: deploy\win-apps\*.7z
    name: win-apps
  - path: deploy\win-client\*.7z
    name: win-client
  - path: deploy\win-manager\*.7z
    name: win-manager

before_test:
  - if %TOOLCHAIN_VERSION%==16.0 curl -fsSL https://github.com/csoltenborn/GoogleTestAdapter/releases/download/v0.18.0/GoogleTestAdapter-0.18.0.vsix -o C:\projects\GoogleTestAdapter.zip
  - if %TOOLCHAIN_VERSION%==16.0 call 7z.exe x C:\projects\GoogleTestAdapter.zip -oC:\projects\GoogleTestAdapter -aoa

test_script:
  - if %TOOLCHAIN_VERSION%==16.0 call vstest.console.exe win_build\Build\%platform%\%configuration%\unittests.exe /TestAdapterPath:C:\projects\GoogleTestAdapter /logger:Appveyor

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
